# Generated by Django 2.2 on 2019-06-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190612_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessories',
            new_name='Accessory',
        ),
        migrations.AddField(
            model_name='plant',
            name='accessories',
            field=models.ManyToManyField(to='main_app.Accessory'),
        ),
    ]
